@startuml big_picture_diagram

box "CommitLogger"
Actor "CommitUser" as U
Participant "Azure Storage Queue" as Q
end box

box "CommitStore" #LightGreen
Participant "CommitTrigger\n<QueueTrigger Function>" as commitTrigger
Participant "Azure Cosmos DB" as Db
Participant "SearchCommits\n<HttpTrigger Function>" as searchFunc
end box

box "CommitUI"
Participant "CommitsUI\n<Blazor WASM>" as W
Actor "FrontendUser" as FU
end box
U -> Q: POST /api/commitqueue
commitTrigger -> Q: QueueTrigger
commitTrigger -> Db : Insert commit
FU -> W: Looks at commit log UI
W -> searchFunc : Search
searchFunc -> Db : Select commits

@enduml
