name: Validate Pull Request

on:
  pull_request:
    branches:
      - main
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./src/Function"
  DOTNET_VERSION: "8.0.x"

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
      - run: |
          dotnet tool restore
          dotnet csharpier . --check

  build:
    runs-on: windows-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Resolve Project Dependencies Using Dotnet"
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
