name: Render Diagrams

on:
  pull_request:
    branches:
      - main

    paths:
      - "docs/*.puml"

jobs:
  render_diagrams:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Render PlantUML Diagrams
        run: |
          pushd docs
          docker run --rm -v $(pwd):/data dstockhammer/plantuml -tpng -o ./images .
          popd

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Render PlantUML diagrams
